version: '2'
services:
   sapp-production-reporter:
        restart: always
        build: "Domain Software/production_reporter/."
        ports:
          - "8100:80"

   sidecarregistration:
        build: ./spsc-app-registration-sidecar/
        env_file:
          - ./spsc-app-registration-sidecar/config.env
   
